// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/njupt-sakura/hertz/hertz_jwt/biz/dal"
	"github.com/njupt-sakura/hertz/hertz_jwt/biz/mw"
)

func main() {
	dal.Init()
	mw.InitJwt()
	h := server.Default()

	register(h)
	h.Spin()
}
