// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/njupt-sakura/hertz/hertz_jwt/biz/handler"
	"github.com/njupt-sakura/hertz/hertz_jwt/biz/mw"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	// r.GET("/ping", handler.Ping)
	r.POST("/register", handler.Register)
	r.POST("/login", mw.JwtMiddleware.LoginHandler)
	auth := r.Group("/auth" /* prefix */, mw.JwtMiddleware.MiddlewareFunc())
	auth.GET("/ping", handler.Ping)
	// your code ...
}
