// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/njupt-sakura/hertz/hertz_session/biz/dal"
	"github.com/njupt-sakura/hertz/hertz_session/biz/mw"
	"github.com/njupt-sakura/hertz/hertz_session/pkg/render"
)

func Init(h *server.Hertz) {
	dal.Init()
	mw.InitSession(h)
	mw.InitCsrf(h)
	render.InitHtml(h)
}

func main() {
	h := server.Default()
	Init(h)

	register(h)
	h.Spin()
}
