// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	handler "github.com/njupt-sakura/hertz/hertz_session/biz/handler"
	"github.com/njupt-sakura/hertz/hertz_session/biz/handler/user"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// your code ...
	r.POST("/logout", user.Logout)
}
