// Code generated by hertz generator.

package user_gorm

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/njupt-sakura/hertz/hertz_gorm/biz/dal/mysql"
	user_gorm "github.com/njupt-sakura/hertz/hertz_gorm/biz/hertz_gen/user_gorm"
	"github.com/njupt-sakura/hertz/hertz_gorm/biz/model"
	"github.com/njupt-sakura/hertz/hertz_gorm/biz/pack"
)

// UpdateUser .
// @router /v1/user/update/:user_id [POST]
func UpdateUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user_gorm.UpdateUserRequest
	err = c.BindAndValidate(&req)

	//! 参数绑定和校验错误, 响应 BadRequest, 状态码 ParamInvalid
	if err != nil {
		// c.String(consts.StatusBadRequest, err.Error())
		resp := &user_gorm.UpdateUserResponse{
			Code: user_gorm.Code_ParamInvalid,
			Msg:  err.Error(),
		}
		c.JSON(consts.StatusBadRequest, resp)
		return
	}

	u := &model.User{}
	u.ID = uint(req.UserID)
	u.Name = req.Name
	u.Gender = int64(req.Gender)
	u.Age = req.Age
	u.Introduce = req.Introduce

	//! 数据库操作失败, 响应 InternalServerError, 状态码 DBErr
	if err = mysql.UpdateUser(u); err != nil {
		resp := &user_gorm.UpdateUserResponse{
			Code: user_gorm.Code_DBErr,
			Msg:  err.Error(),
		}

		c.JSON(consts.StatusInternalServerError, resp)
		return
	}

	//! new 分配内存, 返回指向该类型的零值的指针
	// resp := new(user_gorm.UpdateUserResponse)
	resp := &user_gorm.UpdateUserResponse{Code: user_gorm.Code_Success}
	c.JSON(consts.StatusOK, resp)
}

// DeleteUser .
// @router /v1/user/delete/:user_id [POST]
func DeleteUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user_gorm.DeleteUserRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		// c.String(consts.StatusBadRequest, err.Error())
		resp := &user_gorm.DeleteUserResponse{
			Code: user_gorm.Code_ParamInvalid,
			Msg:  err.Error(),
		}
		c.JSON(consts.StatusBadRequest, resp)
		return
	}

	if err = mysql.DeleteUser(req.UserID); err != nil {
		resp := &user_gorm.DeleteUserResponse{
			Code: user_gorm.Code_DBErr,
			Msg:  err.Error(),
		}

		c.JSON(consts.StatusInternalServerError, resp)
		return
	}

	// resp := new(user_gorm.DeleteUserResponse)
	resp := &user_gorm.DeleteUserResponse{Code: user_gorm.Code_Success}
	c.JSON(consts.StatusOK, resp)
}

// QueryUser .
// @router /v1/user/query/ [POST]
func QueryUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user_gorm.QueryUserRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		// c.String(consts.StatusBadRequest, err.Error())
		resp := &user_gorm.QueryUserResponse{
			Code: user_gorm.Code_ParamInvalid,
			Msg:  err.Error(),
		}
		c.JSON(consts.StatusBadRequest, resp)
		return
	}

	users, total, err := mysql.QueryUser(req.Keyword, req.Page, req.PageSize)
	if err != nil {
		resp := &user_gorm.QueryUserResponse{
			Code: user_gorm.Code_DBErr,
			Msg:  err.Error(),
		}

		c.JSON(consts.StatusInternalServerError, resp)
		return
	}

	// resp := new(user_gorm.QueryUserResponse)
	resp := &user_gorm.QueryUserResponse{
		Code:  user_gorm.Code_Success,
		Users: pack.Users(users),
		Total: total,
	}

	c.JSON(consts.StatusOK, resp)
}

// CreateUser .
// @router /v1/user/create/ [POST]
func CreateUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user_gorm.CreateUserRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		// c.String(consts.StatusBadRequest, err.Error())
		resp := &user_gorm.CreateUserResponse{
			Code: user_gorm.Code_ParamInvalid,
			Msg:  err.Error(),
		}
		c.JSON(consts.StatusBadRequest, resp)
		return
	}

	users := []*model.User{{
		Name:      req.Name,
		Gender:    int64(req.Gender),
		Age:       req.Age,
		Introduce: req.Introduce,
	}}

	if err = mysql.CreateUser(users); err != nil {
		resp := &user_gorm.CreateUserResponse{
			Code: user_gorm.Code_DBErr,
			Msg:  err.Error(),
		}
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}

	resp := new(user_gorm.CreateUserResponse)
	resp.Code = user_gorm.Code_Success

	c.JSON(consts.StatusOK, resp)
}
