// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	publish "github.com/njupt-sakura/hertz/tiktok_demo/biz/router/publish"
	relation "github.com/njupt-sakura/hertz/tiktok_demo/biz/router/relation"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	relation.Register(r)

	publish.Register(r)

}
