// Code generated by hertz generator.

package user

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	user "github.com/njupt-sakura/hertz/hertz_gorm_gen/biz/model/hertz/user"
	"github.com/njupt-sakura/hertz/hertz_gorm_gen/biz/model/model"
	"github.com/njupt-sakura/hertz/hertz_gorm_gen/biz/model/query"
	"github.com/njupt-sakura/hertz/hertz_gorm_gen/biz/pack"
)

// CreateUserResponse .
// @router /v1/user/create [POST]
func CreateUserResponse(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.CreateUserReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest /* 400 */, err.Error())
		return
	}

	resp := new(user.CreateUserResp)
	err = query.User.WithContext(ctx).Create(&model.User{
		Name:      req.Name,
		Gender:    int32(req.Gender),
		Age:       int32(req.Age),
		Introduce: req.Introduce,
	})

	if err != nil {
		resp.Code = user.Code_ParamInvalid
		resp.Msg = err.Error()
		c.JSON(consts.StatusInternalServerError /* 500 */, resp)
		return
	}

	resp.Code = user.Code_Success
	c.JSON(consts.StatusOK /* 200 */, resp)
}

// QueryUserResponse .
// @router /v1/user/query [POST]
func QueryUserResponse(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.QueryUserReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest /* 400 */, err.Error())
		return
	}

	resp := new(user.QueryUserResp)
	u, exec := query.User, query.User.WithContext(ctx)
	if req.Keyword != "" {
		exec = exec.Where(u.Introduce.Like("%" + req.Keyword + "%"))
	}

	var total int64
	total, err = exec.Count()
	if err != nil {
		resp.Code = user.Code_DBErr
		resp.Msg = err.Error()
		c.JSON(consts.StatusInternalServerError /* 500 */, resp)
		return
	}

	var users []*model.User
	if total > 0 {
		users, err = exec.Limit(int(req.PageSize)).Offset(int(req.PageSize * (req.Page - 1))).Find()
		if err != nil {
			resp.Code = user.Code_DBErr
			resp.Msg = err.Error()
			c.JSON(consts.StatusInternalServerError /* 500 */, resp)
			return
		}
	}

	resp.Code = user.Code_Success
	resp.Total = total
	resp.User = pack.Users(users)

	c.JSON(consts.StatusOK /* 200 */, resp)
}

// UpdateUserResponse .
// @router /v1/user/update/:user_id [POST]
func UpdateUserResponse(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.UpdateUserReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(user.UpdateUserResp)
	u := &model.User{}
	u.ID = req.UserId
	u.Name = req.Name
	u.Gender = int32(req.Gender)
	u.Age = int32(req.Age)
	u.Introduce = req.Introduce
	_, err = query.User.WithContext(ctx).Updates(u)
	if err != nil {
		resp.Code = user.Code_DBErr
		resp.Msg = err.Error()
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}

	resp.Code = user.Code_Success
	c.JSON(consts.StatusOK, resp)
}

// DeleteUserResponse .
// @router /v1/user/delete/:user_id [POST]
func DeleteUserResponse(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.DeleteUserReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(user.UpdateUserResp)
	_, err = query.User.WithContext(ctx).Where(query.User.ID.Eq(req.UserId)).Delete()
	if err != nil {
		resp.Code = user.Code_DBErr
		resp.Msg = err.Error()
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}

	resp.Code = user.Code_Success
	c.JSON(consts.StatusOK, resp)
}
