// Code generated by thriftgo (0.4.1). DO NOT EDIT.

package user_gorm

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type Code int64

const (
	Code_Success      Code = 1
	Code_ParamInvalid Code = 2
	Code_DBErr        Code = 3
)

func (p Code) String() string {
	switch p {
	case Code_Success:
		return "Success"
	case Code_ParamInvalid:
		return "ParamInvalid"
	case Code_DBErr:
		return "DBErr"
	}
	return "<UNSET>"
}

func CodeFromString(s string) (Code, error) {
	switch s {
	case "Success":
		return Code_Success, nil
	case "ParamInvalid":
		return Code_ParamInvalid, nil
	case "DBErr":
		return Code_DBErr, nil
	}
	return Code(0), fmt.Errorf("not a valid Code string")
}

func CodePtr(v Code) *Code { return &v }
func (p *Code) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = Code(result.Int64)
	return
}

func (p *Code) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type Gender int64

const (
	Gender_Unknown Gender = 0
	Gender_Male    Gender = 1
	Gender_Female  Gender = 2
)

func (p Gender) String() string {
	switch p {
	case Gender_Unknown:
		return "Unknown"
	case Gender_Male:
		return "Male"
	case Gender_Female:
		return "Female"
	}
	return "<UNSET>"
}

func GenderFromString(s string) (Gender, error) {
	switch s {
	case "Unknown":
		return Gender_Unknown, nil
	case "Male":
		return Gender_Male, nil
	case "Female":
		return Gender_Female, nil
	}
	return Gender(0), fmt.Errorf("not a valid Gender string")
}

func GenderPtr(v Gender) *Gender { return &v }
func (p *Gender) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = Gender(result.Int64)
	return
}

func (p *Gender) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type User struct {
	UserId    int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	Name      string `thrift:"name,2" frugal:"2,default,string" json:"name"`
	Gender    Gender `thrift:"gender,3" frugal:"3,default,Gender" json:"gender"`
	Age       int64  `thrift:"age,4" frugal:"4,default,i64" json:"age"`
	Introduce string `thrift:"introduce,5" frugal:"5,default,string" json:"introduce"`
}

func NewUser() *User {
	return &User{}
}

func (p *User) InitDefault() {
}

func (p *User) GetUserId() (v int64) {
	return p.UserId
}

func (p *User) GetName() (v string) {
	return p.Name
}

func (p *User) GetGender() (v Gender) {
	return p.Gender
}

func (p *User) GetAge() (v int64) {
	return p.Age
}

func (p *User) GetIntroduce() (v string) {
	return p.Introduce
}
func (p *User) SetUserId(val int64) {
	p.UserId = val
}
func (p *User) SetName(val string) {
	p.Name = val
}
func (p *User) SetGender(val Gender) {
	p.Gender = val
}
func (p *User) SetAge(val int64) {
	p.Age = val
}
func (p *User) SetIntroduce(val string) {
	p.Introduce = val
}

func (p *User) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("User(%+v)", *p)
}

var fieldIDToName_User = map[int16]string{
	1: "user_id",
	2: "name",
	3: "gender",
	4: "age",
	5: "introduce",
}

type CreateUserRequest struct {
	Name      string `thrift:"name,1" frugal:"1,default,string" json:"name"`
	Gender    Gender `thrift:"gender,2" frugal:"2,default,Gender" json:"gender"`
	Age       int64  `thrift:"age,3" frugal:"3,default,i64" json:"age"`
	Introduce string `thrift:"introduce,4" frugal:"4,default,string" json:"introduce"`
}

func NewCreateUserRequest() *CreateUserRequest {
	return &CreateUserRequest{}
}

func (p *CreateUserRequest) InitDefault() {
}

func (p *CreateUserRequest) GetName() (v string) {
	return p.Name
}

func (p *CreateUserRequest) GetGender() (v Gender) {
	return p.Gender
}

func (p *CreateUserRequest) GetAge() (v int64) {
	return p.Age
}

func (p *CreateUserRequest) GetIntroduce() (v string) {
	return p.Introduce
}
func (p *CreateUserRequest) SetName(val string) {
	p.Name = val
}
func (p *CreateUserRequest) SetGender(val Gender) {
	p.Gender = val
}
func (p *CreateUserRequest) SetAge(val int64) {
	p.Age = val
}
func (p *CreateUserRequest) SetIntroduce(val string) {
	p.Introduce = val
}

func (p *CreateUserRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateUserRequest(%+v)", *p)
}

var fieldIDToName_CreateUserRequest = map[int16]string{
	1: "name",
	2: "gender",
	3: "age",
	4: "introduce",
}

type CreateUserResponse struct {
	Code Code   `thrift:"code,1" frugal:"1,default,Code" json:"code"`
	Msg  string `thrift:"msg,2" frugal:"2,default,string" json:"msg"`
}

func NewCreateUserResponse() *CreateUserResponse {
	return &CreateUserResponse{}
}

func (p *CreateUserResponse) InitDefault() {
}

func (p *CreateUserResponse) GetCode() (v Code) {
	return p.Code
}

func (p *CreateUserResponse) GetMsg() (v string) {
	return p.Msg
}
func (p *CreateUserResponse) SetCode(val Code) {
	p.Code = val
}
func (p *CreateUserResponse) SetMsg(val string) {
	p.Msg = val
}

func (p *CreateUserResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateUserResponse(%+v)", *p)
}

var fieldIDToName_CreateUserResponse = map[int16]string{
	1: "code",
	2: "msg",
}

type QueryUserRequest struct {
	Keyword  *string `thrift:"Keyword,1,optional" frugal:"1,optional,string" json:"Keyword,omitempty"`
	Page     int64   `thrift:"page,2" frugal:"2,default,i64" json:"page"`
	PageSize int64   `thrift:"page_size,3" frugal:"3,default,i64" json:"page_size"`
}

func NewQueryUserRequest() *QueryUserRequest {
	return &QueryUserRequest{}
}

func (p *QueryUserRequest) InitDefault() {
}

var QueryUserRequest_Keyword_DEFAULT string

func (p *QueryUserRequest) GetKeyword() (v string) {
	if !p.IsSetKeyword() {
		return QueryUserRequest_Keyword_DEFAULT
	}
	return *p.Keyword
}

func (p *QueryUserRequest) GetPage() (v int64) {
	return p.Page
}

func (p *QueryUserRequest) GetPageSize() (v int64) {
	return p.PageSize
}
func (p *QueryUserRequest) SetKeyword(val *string) {
	p.Keyword = val
}
func (p *QueryUserRequest) SetPage(val int64) {
	p.Page = val
}
func (p *QueryUserRequest) SetPageSize(val int64) {
	p.PageSize = val
}

func (p *QueryUserRequest) IsSetKeyword() bool {
	return p.Keyword != nil
}

func (p *QueryUserRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("QueryUserRequest(%+v)", *p)
}

var fieldIDToName_QueryUserRequest = map[int16]string{
	1: "Keyword",
	2: "page",
	3: "page_size",
}

type QueryUserResponse struct {
	Code  Code    `thrift:"code,1" frugal:"1,default,Code" json:"code"`
	Msg   string  `thrift:"msg,2" frugal:"2,default,string" json:"msg"`
	Users []*User `thrift:"users,3" frugal:"3,default,list<User>" json:"users"`
	Total int64   `thrift:"total,4" frugal:"4,default,i64" json:"total"`
}

func NewQueryUserResponse() *QueryUserResponse {
	return &QueryUserResponse{}
}

func (p *QueryUserResponse) InitDefault() {
}

func (p *QueryUserResponse) GetCode() (v Code) {
	return p.Code
}

func (p *QueryUserResponse) GetMsg() (v string) {
	return p.Msg
}

func (p *QueryUserResponse) GetUsers() (v []*User) {
	return p.Users
}

func (p *QueryUserResponse) GetTotal() (v int64) {
	return p.Total
}
func (p *QueryUserResponse) SetCode(val Code) {
	p.Code = val
}
func (p *QueryUserResponse) SetMsg(val string) {
	p.Msg = val
}
func (p *QueryUserResponse) SetUsers(val []*User) {
	p.Users = val
}
func (p *QueryUserResponse) SetTotal(val int64) {
	p.Total = val
}

func (p *QueryUserResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("QueryUserResponse(%+v)", *p)
}

var fieldIDToName_QueryUserResponse = map[int16]string{
	1: "code",
	2: "msg",
	3: "users",
	4: "total",
}

type DeleteUserRequest struct {
	UserId int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
}

func NewDeleteUserRequest() *DeleteUserRequest {
	return &DeleteUserRequest{}
}

func (p *DeleteUserRequest) InitDefault() {
}

func (p *DeleteUserRequest) GetUserId() (v int64) {
	return p.UserId
}
func (p *DeleteUserRequest) SetUserId(val int64) {
	p.UserId = val
}

func (p *DeleteUserRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteUserRequest(%+v)", *p)
}

var fieldIDToName_DeleteUserRequest = map[int16]string{
	1: "user_id",
}

type DeleteUserResponse struct {
	Code Code   `thrift:"code,1" frugal:"1,default,Code" json:"code"`
	Msg  string `thrift:"msg,2" frugal:"2,default,string" json:"msg"`
}

func NewDeleteUserResponse() *DeleteUserResponse {
	return &DeleteUserResponse{}
}

func (p *DeleteUserResponse) InitDefault() {
}

func (p *DeleteUserResponse) GetCode() (v Code) {
	return p.Code
}

func (p *DeleteUserResponse) GetMsg() (v string) {
	return p.Msg
}
func (p *DeleteUserResponse) SetCode(val Code) {
	p.Code = val
}
func (p *DeleteUserResponse) SetMsg(val string) {
	p.Msg = val
}

func (p *DeleteUserResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteUserResponse(%+v)", *p)
}

var fieldIDToName_DeleteUserResponse = map[int16]string{
	1: "code",
	2: "msg",
}

type UpdateUserRequest struct {
	UserId    int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	Name      string `thrift:"name,2" frugal:"2,default,string" json:"name"`
	Gender    Gender `thrift:"gender,3" frugal:"3,default,Gender" json:"gender"`
	Age       int64  `thrift:"age,4" frugal:"4,default,i64" json:"age"`
	Introduce string `thrift:"introduce,5" frugal:"5,default,string" json:"introduce"`
}

func NewUpdateUserRequest() *UpdateUserRequest {
	return &UpdateUserRequest{}
}

func (p *UpdateUserRequest) InitDefault() {
}

func (p *UpdateUserRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *UpdateUserRequest) GetName() (v string) {
	return p.Name
}

func (p *UpdateUserRequest) GetGender() (v Gender) {
	return p.Gender
}

func (p *UpdateUserRequest) GetAge() (v int64) {
	return p.Age
}

func (p *UpdateUserRequest) GetIntroduce() (v string) {
	return p.Introduce
}
func (p *UpdateUserRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *UpdateUserRequest) SetName(val string) {
	p.Name = val
}
func (p *UpdateUserRequest) SetGender(val Gender) {
	p.Gender = val
}
func (p *UpdateUserRequest) SetAge(val int64) {
	p.Age = val
}
func (p *UpdateUserRequest) SetIntroduce(val string) {
	p.Introduce = val
}

func (p *UpdateUserRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateUserRequest(%+v)", *p)
}

var fieldIDToName_UpdateUserRequest = map[int16]string{
	1: "user_id",
	2: "name",
	3: "gender",
	4: "age",
	5: "introduce",
}

type UpdateUserResponse struct {
	Code Code   `thrift:"code,1" frugal:"1,default,Code" json:"code"`
	Msg  string `thrift:"msg,2" frugal:"2,default,string" json:"msg"`
}

func NewUpdateUserResponse() *UpdateUserResponse {
	return &UpdateUserResponse{}
}

func (p *UpdateUserResponse) InitDefault() {
}

func (p *UpdateUserResponse) GetCode() (v Code) {
	return p.Code
}

func (p *UpdateUserResponse) GetMsg() (v string) {
	return p.Msg
}
func (p *UpdateUserResponse) SetCode(val Code) {
	p.Code = val
}
func (p *UpdateUserResponse) SetMsg(val string) {
	p.Msg = val
}

func (p *UpdateUserResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateUserResponse(%+v)", *p)
}

var fieldIDToName_UpdateUserResponse = map[int16]string{
	1: "code",
	2: "msg",
}

type UserService interface {
	UpdateUser(ctx context.Context, req *UpdateUserRequest) (r *UpdateUserResponse, err error)

	DeleteUser(ctx context.Context, req *DeleteUserRequest) (r *DeleteUserResponse, err error)

	QueryUser(ctx context.Context, req *QueryUserRequest) (r *QueryUserResponse, err error)

	CreateUser(ctx context.Context, req *CreateUserRequest) (r *CreateUserResponse, err error)
}

type UserServiceUpdateUserArgs struct {
	Req *UpdateUserRequest `thrift:"req,1" frugal:"1,default,UpdateUserRequest" json:"req"`
}

func NewUserServiceUpdateUserArgs() *UserServiceUpdateUserArgs {
	return &UserServiceUpdateUserArgs{}
}

func (p *UserServiceUpdateUserArgs) InitDefault() {
}

var UserServiceUpdateUserArgs_Req_DEFAULT *UpdateUserRequest

func (p *UserServiceUpdateUserArgs) GetReq() (v *UpdateUserRequest) {
	if !p.IsSetReq() {
		return UserServiceUpdateUserArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceUpdateUserArgs) SetReq(val *UpdateUserRequest) {
	p.Req = val
}

func (p *UserServiceUpdateUserArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceUpdateUserArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUpdateUserArgs(%+v)", *p)
}

var fieldIDToName_UserServiceUpdateUserArgs = map[int16]string{
	1: "req",
}

type UserServiceUpdateUserResult struct {
	Success *UpdateUserResponse `thrift:"success,0,optional" frugal:"0,optional,UpdateUserResponse" json:"success,omitempty"`
}

func NewUserServiceUpdateUserResult() *UserServiceUpdateUserResult {
	return &UserServiceUpdateUserResult{}
}

func (p *UserServiceUpdateUserResult) InitDefault() {
}

var UserServiceUpdateUserResult_Success_DEFAULT *UpdateUserResponse

func (p *UserServiceUpdateUserResult) GetSuccess() (v *UpdateUserResponse) {
	if !p.IsSetSuccess() {
		return UserServiceUpdateUserResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceUpdateUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateUserResponse)
}

func (p *UserServiceUpdateUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceUpdateUserResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUpdateUserResult(%+v)", *p)
}

var fieldIDToName_UserServiceUpdateUserResult = map[int16]string{
	0: "success",
}

type UserServiceDeleteUserArgs struct {
	Req *DeleteUserRequest `thrift:"req,1" frugal:"1,default,DeleteUserRequest" json:"req"`
}

func NewUserServiceDeleteUserArgs() *UserServiceDeleteUserArgs {
	return &UserServiceDeleteUserArgs{}
}

func (p *UserServiceDeleteUserArgs) InitDefault() {
}

var UserServiceDeleteUserArgs_Req_DEFAULT *DeleteUserRequest

func (p *UserServiceDeleteUserArgs) GetReq() (v *DeleteUserRequest) {
	if !p.IsSetReq() {
		return UserServiceDeleteUserArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceDeleteUserArgs) SetReq(val *DeleteUserRequest) {
	p.Req = val
}

func (p *UserServiceDeleteUserArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceDeleteUserArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceDeleteUserArgs(%+v)", *p)
}

var fieldIDToName_UserServiceDeleteUserArgs = map[int16]string{
	1: "req",
}

type UserServiceDeleteUserResult struct {
	Success *DeleteUserResponse `thrift:"success,0,optional" frugal:"0,optional,DeleteUserResponse" json:"success,omitempty"`
}

func NewUserServiceDeleteUserResult() *UserServiceDeleteUserResult {
	return &UserServiceDeleteUserResult{}
}

func (p *UserServiceDeleteUserResult) InitDefault() {
}

var UserServiceDeleteUserResult_Success_DEFAULT *DeleteUserResponse

func (p *UserServiceDeleteUserResult) GetSuccess() (v *DeleteUserResponse) {
	if !p.IsSetSuccess() {
		return UserServiceDeleteUserResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceDeleteUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*DeleteUserResponse)
}

func (p *UserServiceDeleteUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceDeleteUserResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceDeleteUserResult(%+v)", *p)
}

var fieldIDToName_UserServiceDeleteUserResult = map[int16]string{
	0: "success",
}

type UserServiceQueryUserArgs struct {
	Req *QueryUserRequest `thrift:"req,1" frugal:"1,default,QueryUserRequest" json:"req"`
}

func NewUserServiceQueryUserArgs() *UserServiceQueryUserArgs {
	return &UserServiceQueryUserArgs{}
}

func (p *UserServiceQueryUserArgs) InitDefault() {
}

var UserServiceQueryUserArgs_Req_DEFAULT *QueryUserRequest

func (p *UserServiceQueryUserArgs) GetReq() (v *QueryUserRequest) {
	if !p.IsSetReq() {
		return UserServiceQueryUserArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceQueryUserArgs) SetReq(val *QueryUserRequest) {
	p.Req = val
}

func (p *UserServiceQueryUserArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceQueryUserArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceQueryUserArgs(%+v)", *p)
}

var fieldIDToName_UserServiceQueryUserArgs = map[int16]string{
	1: "req",
}

type UserServiceQueryUserResult struct {
	Success *QueryUserResponse `thrift:"success,0,optional" frugal:"0,optional,QueryUserResponse" json:"success,omitempty"`
}

func NewUserServiceQueryUserResult() *UserServiceQueryUserResult {
	return &UserServiceQueryUserResult{}
}

func (p *UserServiceQueryUserResult) InitDefault() {
}

var UserServiceQueryUserResult_Success_DEFAULT *QueryUserResponse

func (p *UserServiceQueryUserResult) GetSuccess() (v *QueryUserResponse) {
	if !p.IsSetSuccess() {
		return UserServiceQueryUserResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceQueryUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*QueryUserResponse)
}

func (p *UserServiceQueryUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceQueryUserResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceQueryUserResult(%+v)", *p)
}

var fieldIDToName_UserServiceQueryUserResult = map[int16]string{
	0: "success",
}

type UserServiceCreateUserArgs struct {
	Req *CreateUserRequest `thrift:"req,1" frugal:"1,default,CreateUserRequest" json:"req"`
}

func NewUserServiceCreateUserArgs() *UserServiceCreateUserArgs {
	return &UserServiceCreateUserArgs{}
}

func (p *UserServiceCreateUserArgs) InitDefault() {
}

var UserServiceCreateUserArgs_Req_DEFAULT *CreateUserRequest

func (p *UserServiceCreateUserArgs) GetReq() (v *CreateUserRequest) {
	if !p.IsSetReq() {
		return UserServiceCreateUserArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceCreateUserArgs) SetReq(val *CreateUserRequest) {
	p.Req = val
}

func (p *UserServiceCreateUserArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceCreateUserArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceCreateUserArgs(%+v)", *p)
}

var fieldIDToName_UserServiceCreateUserArgs = map[int16]string{
	1: "req",
}

type UserServiceCreateUserResult struct {
	Success *CreateUserResponse `thrift:"success,0,optional" frugal:"0,optional,CreateUserResponse" json:"success,omitempty"`
}

func NewUserServiceCreateUserResult() *UserServiceCreateUserResult {
	return &UserServiceCreateUserResult{}
}

func (p *UserServiceCreateUserResult) InitDefault() {
}

var UserServiceCreateUserResult_Success_DEFAULT *CreateUserResponse

func (p *UserServiceCreateUserResult) GetSuccess() (v *CreateUserResponse) {
	if !p.IsSetSuccess() {
		return UserServiceCreateUserResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceCreateUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateUserResponse)
}

func (p *UserServiceCreateUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceCreateUserResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceCreateUserResult(%+v)", *p)
}

var fieldIDToName_UserServiceCreateUserResult = map[int16]string{
	0: "success",
}
